import {
  ArrowLeftIcon,
  ArrowRightIcon,
  CaretSortIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  Cross2Icon,
  DashboardIcon,
  DotFilledIcon,
  DotsHorizontalIcon,
  ExitIcon,
  GearIcon,
  MagnifyingGlassIcon,
} from '@radix-ui/react-icons';
import { ShoppingCart } from 'lucide-react';

export const Icons = {
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  caretSort: CaretSortIcon,
  check: CheckIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  cross: Cross2Icon,
  dashboard: DashboardIcon,
  dot: DotFilledIcon,
  dotsHorizontal: DotsHorizontalIcon,
  logout: ExitIcon,
  settings: GearIcon,
  search: MagnifyingGlassIcon,
  cart: ShoppingCart,
};
